# Generated by Django 4.0.4 on 2022-05-07 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 17, 1, 44, 282585), verbose_name='DateTime'),
        ),
    ]
